### ISSUE TITLE
Backup feature? Local/Dropbox/Google Drive

### ISSUE THREAD

**Issue by Wixxi** [medicalid/issues#65] opened 2016-10-20 07:03 UTC
Hey  I helped you translate your Medical ID app to dutch.
One major feature I'm missing is backup to dropbox/google drive or just local.
Just switched phones and had to retyp everything.
And an export to just text isn't that usefull.

You think you can add this in an update soon?

Greetz,
Jens

**Comment by laurentpellegrino** [comment] 2016-10-22 06:55
Yes, will definitively be added.

Duplicate of https://github.com/medicalid/issues/issues/53.

**Closed as completed by laurentpellegrino** 2016-10-22 06:55 UTC
Labels: duplicate
